import { ProgramBlueprint, Rest } from '@/models/blueprint-models';
import { toBigNumberJSON, toLocalDateJSON } from '@/models/storage/versions/latest';
import { programBlueprintMigrations } from '@/models/storage/versions/migrations';
import BigNumber from 'bignumber.js';
import { LocalDate } from '@js-joda/core';

type SessionSeed = [string, string];
type ProgramSeed = [string, SessionSeed[]];

// Compact transcription of the modern templates in Hersovyac's Upper/Lower guide.
// A `>` joins exercises that are prescribed as a superset; `;` starts a new block.
const seeds: ProgramSeed[] = [
  ['Hersovyac - Beginner Upper/Lower', [['Upper 1','BB Bench Press|3|6>DB Row|3|8;Seated BB Press|3|6>Pronated Pull-Up|3|8;Dips|3|8>DB Lateral Raise|3|10;EZ Bar Curl|3|8>Cable Triceps Extension|3|8'],['Lower 1','Back Squat|3|5>Tibialis Raise|3|15;Deadlift|1|3>Calf Raise|3|10;Leg Extension|3|10>Leg Curl|3|8;Back Extension|3|10>Hanging Knee Raise|3|10'],['Upper 2','Seated DB Press|5|5>Neutral Grip Pull-Up|5|5;Incline DB Press|5|5>Pronated Pull-Up|3|8;Close Grip Bench Press|3|5>DB Hammer Curl|3|8;DB Rear Delt Raise|3|12>DB Lateral Raise|3|10'],['Lower 2','Romanian Deadlift|3|8>Calf Raise|3|15;Leg Press|3|8>Tibialis Raise|3|15;DB Walking Lunge|2|8;Back Extension|3|10>Hanging Knee Raise|3|10']]],
  ['Hersovyac - Intermediate Upper/Lower', [['Upper 1','Seated BB Press|3|5>Weighted Neutral Chin-Up|4|6;DB Incline Press|3|6>Chest Supported Row|3|8;Weighted Dips|3|8>Alternating DB Curl|3|7;Pec Deck|3|8>Reverse Pec Deck|3|10;Rope Extension|3|8>Rope Curl|3|8'],['Lower 1','High Bar Back Squat|5|5>Tibialis Raise|5|15;Front Squat|3|5>Calf Raise|3|10;Leg Press|2|8>Leg Press Calf Raise|2|12;Leg Curl|3|8>Leg Extension|3|10;Back Extension|3|10>Hanging Knee Raise|3|10'],['Upper 2','BB Bench Press|3|5>Pull-Up|3|8;Larsen Close Grip Press|3|5>Chest Supported Row|3|8;Seated DB Press|3|8>EZ Bar Upright Row|3|8;EZ Bar Triceps Pullover|3|8>DB Hammer Curl|3|7'],['Lower 2','Block Pull|3|5>Calf Raise|3|15;DB Romanian Deadlift|3|10>Seated Calf Raise|2|20;Smith Squat|3|7>Tibialis Raise|3|15;Back Extension|3|10>Hanging Knee Raise|3|10']]],
  ['Hersovyac - Advanced Upper/Lower', [['Upper 1','Smith High Incline Press|2|6>Chest Supported Row (lat)|3|8;Smith Low Incline Press|2|6>Chest Supported Row (traps)|3|8;Reverse Grip Smith Bench|2|6>Wall EZ Curl|3|6;Overhead Rope Extension|3|8>Rope Curl|3|8;Cable Rear Raise|2|12>Cable Lateral Raise|2|10>Cable Y Raise|2|8'],['Lower 1','Smith Squat|3|8>Tibialis Raise|3|15;Leg Press|2|10>Leg Press Calf Raise|2|15;Leg Curl|3|8>Leg Extension|3|12;Hip Adductor|3|10>Hip Abductor|3|20;Single Leg Back Extension|2|10>Hanging Knee Raise|3|10'],['Upper 2','Flat Chest Press|2|8>Lat Machine Pulldown|3|8;Incline Chest Press|2|8>Wide Pull-Up|3|8;Decline Press|3|8>Machine Pullover|3|10;Cross Body Cable Extension|3|8>DB Pinwheel Curl|3|7;Pec Deck|2|10>Reverse Pec Deck|2|10>DB Lateral Raise|2|10'],['Lower 2','Stiff Leg Pull|2|5>Tibialis Raise|2|15;DB Romanian Deadlift|3|10>Seated Calf Raise|2|20;Nordic Hamstring Curl|3|5>Reverse Nordic|3|8;Hip Thrust|2|10>Donkey Calf Raise|2|20;Back Extension|2|10>Hanging Knee Raise|3|10']]],
  ['Hersovyac - Old School Bodybuilding', [['Upper 1','DB Bench Press|3|6>Weighted Chin-Up|3|7;BB Incline Press|3|8>Wide Grip Pull-Up|3|8;Cable Chest Fly|3|10>DB Pullover|3|10;Rope Extension|4|8>Rope Curl|4|8;Cable Rear Raise|2|12>Cable Lateral Raise|2|10>Cable Y Raise|2|8'],['Lower 1','Back Squat|3|8>Tibialis Raise|3|15;Front Squat|4|5>Donkey Calf Raise|4|15;DB Lying Leg Curl|3|8>Bulgarian Split Squat|3|8;Back Extension|3|10>Hanging Knee Raise|3|10>Vacuum|3|1'],['Upper 2','Seated DB Press|3|6>Sternum Pulldown|4|8;DB Incline Press|3|8>Behind Neck Pulldown|4|8;Guillotine BB Press|3|6>Chest Supported DB Row|4|8;EZ Bar Triceps Pullover|4|8>DB Concentration Curl|4|8'],['Lower 2','BB Romanian Deadlift|3|7>DB Calf Raise|3|15;Back Squat|1|15>Tibialis Raise|3|15;Front Hack Squat|4|8>DB Lying Leg Curl|4|8;Single Leg Back Extension|3|10>Hanging Knee Raise|3|10>Vacuum|3|1']]],
  ['Hersovyac - Home Gym Upper/Lower', [['Upper 1','BB Bench Press|3|6>Weighted Chin-Up|3|7;DB Incline Press|3|8>Wide Grip Pull-Up|3|8;DB High Incline Press|3|8>Band Pull Apart|3|10;Band Overhead Extension|3|8>DB Incline Curl|3|8;DB Rear Raise|2|12>DB Lateral Raise|2|10>DB Front Raise|2|8'],['Lower 1','Back Squat|3|8>Tibialis Raise|3|15;Front Squat|4|5>Donkey Calf Raise|4|15;DB Lying Leg Curl|3|8>Bulgarian Split Squat|3|8;Band Good Morning|3|12>Hanging Knee Raise|3|10'],['Upper 2','Seated Press|3|6>DB Row|3|8;Larsen Close Grip Press|3|6>DB Row|3|8;Ring Push-Up|3|8>Ring Inverted Row|3|8;EZ Bar Pullover and Press|4|8>DB Concentration Curl|4|8'],['Lower 2','BB Romanian Deadlift|3|6>DB Calf Raise|3|15;DB Romanian Deadlift|3|10>Tibialis Raise|3|15;Cyclist Squat|3|8>DB Lying Leg Curl|3|8;Band Good Morning|3|12>Hanging Knee Raise|3|10>Vacuum|3|1']]],
  ['Hersovyac - Powerlifting Upper/Lower', [['Upper 1','BB Bench Press|3|3>Chin-Up|3|8>Band Pull Apart|3|15;DB Incline Press|3|8>Wide Grip Pulldown|3|8;Weighted Dips|3|8>DB Hammer Curl|3|8'],['Lower 1','Back Squat|3|3>Tibialis Raise|3|15;Paused Front Squat|3|3>Calf Raise|3|15;Leg Extension|3|10>Leg Curl|3|8'],['Upper 2','Seated Press|3|3>Chin-Up|3|8;Close Grip Bench Press|3|6>DB Row|3|8;Cable Extension|4|8>Cable Curl|4|8'],['Lower 2','Stiff Leg Block Pull|2|3>DB Calf Raise|2|15;Anderson Squat|3|5>Seated Calf Raise|3|15;BB Shrug|5|5>Seated Cable Row|5|8']]],
  ['Hersovyac - Senior Upper/Lower', [['Upper 1','DB Incline Press|3|10>Neutral Chin-Up|3|8>Band Pull Apart|3|15;DB Seated Press|3|8>Chest Supported Row|3|8;Rope Extension|3|10>Rope Curl|3|8'],['Lower 1','Banded Leg Press|3|10>Tibialis Raise|3|15;Leg Extension|3|12>Leg Curl|3|8;Smith Squat|3|8>Seated Calf Raise|2|20'],['Upper 2','Dips|3|8>Ring Chin-Up|3|8>Band Pull Apart|3|15;Ring Push-Up|3|8>Ring Inverted Row|3|8;Cable Triceps Extension|4|8>Cable Biceps Curl|4|8'],['Lower 2','DB Romanian Deadlift|3|10>Calf Raise|3|15;Bulgarian Split Squat|3|8>Tibialis Raise|3|15;Seated Hip Adductor|3|12>Seated Hip Abductor|3|15']]],
  ['Hersovyac - Busy Chad 3x Upper/Lower', [['Upper 1','Close Grip Bench Press|3|6>Neutral Chin-Up|3|6;Cable Extension|3|8>Cable Curl|3|8;Reverse Pec Deck|3|12>DB Lateral Raise|3|10>DB Front Raise|3|8'],['Lower 1','Front Squat|3|6>Tibialis Raise|3|15;Leg Extension|3|12>Leg Curl|3|8;Back Extension|3|10>Hanging Knee Raise|3|10'],['Upper 2','Seated Press|3|6>Pull-Up|3|8>Band Pull Apart|3|15;Ring Push-Up|3|8>Ring Inverted Row|3|8;Cable Triceps Extension|4|8>Cable Biceps Curl|4|8'],['Lower 2','Rack Pull|3|6>Calf Raise|3|15;Seated Hip Adductor|3|12>Seated Hip Abductor|3|15;Back Extension|3|15>Hanging Knee Raise|3|10']]],
  ['Hersovyac - Busy Chad 6x Upper/Lower', [['Upper 1','Larsen Press|3|6>Chest Supported Row|3|8>Band L Fly|3|10'],['Lower 1','Back Squat|5|5>Tibialis Raise|3|15>Leg Curl|5|8'],['Upper 2','Seated Press|3|6>Weighted Pull-Up|3|6>Band Pull Apart|3|15'],['Lower 2','BB Romanian Deadlift|3|8>Calf Raise|3|15>Leg Extension|3|10'],['Upper 3','Weighted Dips|3|7>Hammer Curl|3|8>Reverse Pec Deck|3|12'],['Lower 3','Bulgarian Split Squat|3|8>Tibialis Raise|3|15>Leg Curl|3|8']]],
  ['Hersovyac - Summer Break 6x Upper/Lower', [['Upper 1','Seated Press|3|6>Weighted Chin-Up|3|6>Band L Fly|3|10;BB Incline Press|3|6>Weighted Pull-Up|3|8;EZ Bar Pullover and Press|3|8>DB Hammer Curl|3|7'],['Lower 1','Front Squat|5|5>Tibialis Raise|5|15;Back Squat|3|10>Calf Raise|3|15;Leg Press|3|8>Seated Leg Curl|3|8'],['Upper 2','Reverse Grip Bench|5|5>DB Row|5|10>Band L Fly|5|10;DB Incline Press|3|6>Sternum Pulldown|3|8;DB Fly|3|8>High Cable Row|3|8'],['Lower 2','Snatch Grip RDL|5|5>Seated Calf Raise|5|15;Romanian Deadlift|3|6>Calf Raise|3|15;Smith Hack Squat|3|7>Seated Leg Curl|3|8'],['Upper 3','Smith Incline Press|3|8>Upright Row|3|8>Band L Fly|3|10;Smith Press|3|6>Neutral Grip Pulldown|3|8;Weighted Dips|3|8>Cheat Curl|3|6'],['Lower 3','Power Row|3|6>Donkey Calf Raise|3|20;Hip Thrust|3|8>Calf Raise|3|15;Shrug|5|5>Leg Extension|3|12']]],
  ['Hersovyac - Personal Upper/Lower', [['Upper 1','High Incline BB Press|3|6>Weighted Pull-Up|4|6>Band L Fly|3|10;Weighted Dips|3|5>EZ Bar Strict Curl|3|5;Dual Cable Seated Curl|3|7>Cross Body Cable Extension|3|8'],['Lower 1','Rack Pull|3|5>Band Neck Rotation|3|12;Shrug|3|5>Band Neck Extension|3|20;Belt Squat|2|6>Tibialis Raise|3|15;Nordic Hamstring Curl|3|6>Reverse Nordic|3|10'],['Upper 2','Incline Machine Press|3|6>Machine Traps Row|3|8>Band L Fly|3|10;Seated Machine Press|2|7>Machine Lat Row|3|8;Flat Machine Press|3|6>DB Pinwheel Curl|3|7'],['Lower 2','Smith Squat|3|7>Tibialis Raise|3|15;DB Romanian Deadlift|3|10;Leg Extension|4|12>Lying Leg Curl|4|8;Seated Hip Abductor|3|20>Seated Hip Adductor|3|10>Leg Press Calf Raise|3|15']]],
];

function makeProgram([name, sessions]: ProgramSeed): ProgramBlueprint {
  return ProgramBlueprint.fromJSON(programBlueprintMigrations.migrate({ name, lastEdited: toLocalDateJSON(LocalDate.of(2026, 7, 28)), sessions: sessions.map(([sessionName, blocks]) => ({ name: sessionName, notes: 'Hersovyac Upper/Lower guide. Rep target is the lower end of each prescribed range; see exercise notes for the original range.', exercises: blocks.split(';').flatMap((block) => block.split('>').map((entry, index, group) => { const [exerciseName, setCount, reps] = entry.split('|'); return { type: 'WeightedExerciseBlueprint', name: exerciseName ?? '', sets: Number(setCount), repsPerSet: Number(reps), weightIncreaseOnSuccess: toBigNumberJSON(new BigNumber('2.5')), restBetweenSets: Rest.toJSON(Rest.medium), supersetWithNext: index < group.length - 1, notes: 'Hersovyac template - adjust load and use the prescribed rep range from the guide.', link: '' }; })) })) }));
}

export const HersovyacPrograms: Record<string, ProgramBlueprint> = Object.fromEntries(seeds.map((seed, index) => [`6be05c${index}-cc58-4a40-9b8f-0cbce45b7${(100 + index).toString().slice(1)}`, makeProgram(seed)]));
